#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
cd "$ROOT_DIR"

forward_var() {
  local from_name="$1"
  local to_name="$2"
  local value="${!from_name:-}"
  if [[ -n "$value" ]]; then
    export "$to_name=$value"
  fi
}

export PULSIX_ACCESS_HTTP_ENGINE_HTTP_SMOKE_SCRIPT="${PULSIX_ACCESS_BEACON_ENGINE_BEACON_SMOKE_SCRIPT:-scripts/pulsix-access-beacon-smoke.sh}"
export PULSIX_ACCESS_HTTP_ENGINE_SOURCE_CODE="${PULSIX_ACCESS_BEACON_ENGINE_SOURCE_CODE:-trade_beacon_demo}"
export PULSIX_ACCESS_HTTP_ENGINE_REQUEST_ID="${PULSIX_ACCESS_BEACON_ENGINE_REQUEST_ID:-REQ_BEACON_ENGINE_SMOKE_9105}"

for suffix in \
  BASE_URL HEALTH_URL ENGINE_SMOKE_SCRIPT COMPOSE_FILE PAYLOAD EVENT_ID TRACE_ID \
  SCENE_CODE EVENT_CODE STANDARD_TOPIC VERIFY_KAFKA VERIFY_ERROR_LOG \
  EXPECTED_FINAL_ACTION SNAPSHOT_SCENE_CODE SNAPSHOT_VERSION EXPECTED_VERSION \
  KAFKA_BOOTSTRAP_SERVERS GROUP_ID MYSQL_HOST MYSQL_PORT MYSQL_DATABASE MYSQL_USER \
  MYSQL_PASSWORD MYSQL_JDBC_PARAMS REDIS_HOST REDIS_PORT REDIS_DATABASE REDIS_PASSWORD \
  OUT_FILE LOG_FILE CONFIG_FILE TIMEOUT_SECONDS START_WAIT_SECONDS STARTING_OFFSETS \
  ID_SUFFIX ALLOW_FALLBACK_ENGINE_ERROR EXPECTED_FALLBACK_ERROR_CODE EXPECTED_FALLBACK_MODE
  do
  forward_var "PULSIX_ACCESS_BEACON_ENGINE_${suffix}" "PULSIX_ACCESS_HTTP_ENGINE_${suffix}"
done

bash scripts/pulsix-access-http-engine-smoke.sh "$@"
echo "[smoke] Beacon -> Kafka -> Engine smoke passed"
